### ISSUE TITLE
Does not uninstall cleanly, records are left in the WordPress options table.

### ISSUE THREAD

**Issue by pacmaninbw** [NitinPrakash/wc-thanks-redirect#4]
I uninstalled this plugin a month ago. These options are still in the **options** table in the WordPress database for my website:

(411067, 'wctr_global', 'yes', 'yes'),
(411068, 'wctr_thanks_redirect_url', 'https://MY_URL/my-account/thank-you/', 'yes'),
(411069, 'wctr_failed_redirect_url', '', 'yes'),
(411070, 'wctr_thanks_redirect_enable_template_redirect', 'yes', 'yes'),
(411071, 'wctr_wpml_active', 'no', 'yes'),

This is preventing me from overriding the WooCommerce thank you template in my theme.

I have traced the previous records to code in wc-thanks-redirect.php, specifically the function wc_thanks_redirect_settings( $settings, $current_section ) .

I believe the plugin should delete these from the options table when it is uninstalled.

**Comment by nitinprakash** [comment]
@pacmaninbw 

This issue is fixed in Release 4.1.4
https://github.com/NitinPrakash/wc-thanks-redirect/commit/b60c8a5219d9ac3b3cb47fea5a05163a65bc6c52
